# Generated by Django 4.0.4 on 2022-05-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('accountType', models.CharField(choices=[('1', 'Student'), ('2', 'Teacher')], max_length=1)),
                ('classCode', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('1', 'Lesson'), ('2', 'Quiz')], max_length=1)),
                ('score', models.IntegerField(null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithmOcean.account')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.CharField(max_length=30)),
                ('question', models.IntegerField()),
                ('score', models.IntegerField(null=True)),
                ('weight', models.IntegerField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithmOcean.account')),
            ],
        ),
    ]
