# Generated by Django 4.0.5 on 2022-06-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmOcean', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accountType',
            field=models.CharField(choices=[('1', 'Student'), ('2', 'Teacher')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='classCode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
