# Generated by Django 4.0.5 on 2022-06-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithmOcean', '0002_customuser_accounttype_customuser_classcode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
